#!/bin/sh

#pathToImages='/home/namhoon/Dropbox/cropped'
#outFile='testimages.txt'
#find $pathToImages -name "*.png" ! -type d > $outFile

#pathToImages='/home/namhoon/Downloads/data_towncenter/frames_out'
#outFile='testcrop.txt'
#find $pathToImages -name "*.jpg" ! -type d > $outFile

#pathToImages='/home/namhoon/develop/PoseRegression/data/rendout/bigboxtest/pos_bb'
#outFile='pos_bb.txt'
#find $pathToImages -name "*.jpg" ! -type d > $outFile

#pathToImages='/home/namhoon/develop/PoseRegression/data/rendout/pos/loc045001'
#outFile='pos.txt'
#find $pathToImages -name "*.jpg" ! -type d > $outFile

#pathToImages='/home/namhoon/develop/PoseRegression/data/rendout/pos_double/loc045001'
#outFile='pos_double.txt'
#find $pathToImages -name "*.jpg" ! -type d > $outFile

#pathToImages='/home/namhoon/develop/PoseRegression/data/rendout/joints_norm/2D/loc045001'
#outFile='joints_2d.txt'
#find $pathToImages -name "*.txt" ! -type d > $outFile

# real data
#pathToImages='/home/namhoon/develop/PoseRegression/data/cropped'
#outFile='real.txt'
#find $pathToImages -name "*.png" ! -type d > $outFile

# new render with szx szy szz
#pathToImages='/home/namhoon/develop/PoseRegression/data/rendout/tmp_y144_x256/pos'
#outFile='pos_y144_x256.txt'
#find $pathToImages -name "*.jpg" ! -type d > $outFile

# (double) new render with szx szy szz
#pathToImages='/home/namhoon/develop/PoseRegression/data/rendout/tmp_y144_x256_double/pos'
#outFile='pos_y144_x256_double.txt'
#find $pathToImages -name "*.jpg" ! -type d > $outFile

## real data. tmp_y144_x256
#pathToImages='/home/namhoon/develop/towncenter/data/frames_y144_x256_sel'
#outFile='frames_y144_x256_sel.txt'
#find $pathToImages -name "*.png" ! -type d > $outFile

## real data. frame_y144_x256_sel_triple
#pathToImages='/home/namhoon/develop/towncenter/data/frames_y144_x256_sel_triple'
#outFile='frames_y144_x256_sel_triple.txt'
#find $pathToImages -name "*.png" ! -type d > $outFile

# frame_y144_x256_new (covers all heights and it has segmentations)
pathToImages1='/home/namhoon/develop/PoseRegression/data/rendout/tmp_y144_x256_new/pos'
pathToImages2='/home/namhoon/develop/PoseRegression/data/rendout/tmp_y144_x256_new/mask'
outFile1='pos_y144_x256_new.txt'
outFile2='mask_y144_x256_new.txt'
find $pathToImages1 -maxdepth 1 -name "*.jpg" ! -type d > $outFile1
find $pathToImages2 -maxdepth 1 -name "*.jpg" ! -type d > $outFile2








